
genome_targets:
  {organism: "Ramazzottius varieornatus",
   source: "UniProt",
   url: "https://rest.uniprot.org/uniprotkb/stream?compressed=true&format=fasta&query=taxonomy_id:947166"}
  {organism: "Ramazzottius varieornatus",
   source: "NCBI",
   url: "https://api.ncbi.nlm.nih.gov/datasets/v2/genome/accession/GCA_001949185.1/download?include_annotation_type=PROT_FASTA"}

